As we preprocessed the available datasets we get movies information till the year 2017.Now we have to get movies after year 2017 for that we need to extract from wikkipedia and for genres use the TMDB database 
I will be considering american and bollywood movies for years after 2017

In [122]:
import pandas as pd
import numpy as np

In [123]:
link1 = "https://en.wikipedia.org/wiki/List_of_American_films_of_2018"
link2 = "https://en.wikipedia.org/wiki/List_of_Bollywood_films_of_2018"
df1 = pd.read_html(link1, header =0)[2] #using 2 to get the second section on the page(jan - march)
df2 = pd.read_html(link1, header =0)[3] #april-june
df3 = pd.read_html(link1, header =0)[4] #july-september
df4 = pd.read_html(link1, header =0)[5] #october-december

In [124]:
#simarly for bollywood movies
df11 = pd.read_html(link2, header =0)[2]
df21 = pd.read_html(link2, header =0)[3]
df31 = pd.read_html(link2, header =0)[4]
df41 = pd.read_html(link2, header =0)[5]

In [125]:
df_american = df1.append(df2.append(df3.append(df4,ignore_index = True),ignore_index = True),ignore_index = True)
df_american

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2]
1,JANUARY,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3]
2,JANUARY,5,Stratton,Momentum Pictures,"Simon West (director); Duncan Falconer, Warren...",[4]
3,JANUARY,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5]
4,JANUARY,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6]
...,...,...,...,...,...,...
264,DECEMBER,25,Holmes & Watson,Columbia Pictures / Gary Sanchez Productions,Etan Cohen (director/screenplay); Will Ferrell...,[163]
265,DECEMBER,25,Vice,Annapurna Pictures / Plan B Entertainment,Adam McKay (director/screenplay); Christian Ba...,[137]
266,DECEMBER,25,On the Basis of Sex,Focus Features,Mimi Leder (director); Daniel Stiepleman (scre...,[226]
267,DECEMBER,25,Destroyer,Annapurna Pictures,"Karyn Kusama (director); Phil Hay, Matt Manfre...",[258]
268,DECEMBER,28,Black Mirror: Bandersnatch,Netflix,David Slade (director); Charlie Brooker (scree...,[259]

In [126]:
df_bollywood = df11.append(df21.append(df31.append(df41,ignore_index = True),ignore_index = True),ignore_index = True)
df_bollywood

,Opening,Opening.1,Title,Director,Cast,Production house,Ref.
0,JAN,12,1921,Vikram Bhatt,Zareen KhanKaran KundraTobby HinstonSonia Arms...,ASA Productions and Enterprises,[16][17]
1,JAN,12,Kaalakaandi,Akshat Verma,Saif Ali KhanIsha TalwarShenaz TreasuryAkshay ...,Cinestan Film Company,[18][19]
2,JAN,12,Mukkabaaz,Anurag Kashyap,Vineet Kumar SinghZoya HussainRavi KishanJimmy...,"Eros International, Colour Yellow Productions",[20][21]
3,JAN,15,Phir Se...,Kunal Kohli,Jennifer WingetKunal KohliRajit Kapur,"Bombay Film Company Ltd, Netflix",[22][23][24]
4,JAN,19,My Birthday Song,Samir Soni,Sanjay SuriNora FatehiPitobash,Kahwa entertainment,[25][26]
...,...,...,...,...,...,...,...
99,NOV,30,Rajma Chawal,Leena Yadav,Rishi KapoorAnirudh TanwarAmyra Dastur,"SaarthiE, Netflix",[127]
100,DEC,7,Kedarnath,Abhishek Kapoor,Sushant Singh RajputSara Ali Khan,"RSVP Movies, Guy in the Sky Pictures",[128][129]
101,DEC,14,Ascharyachakit!,Samit Kakkad,Priyanka BoseVaibhav Raj GuptaAnkit RaajAnangs...,"Yoodlee films, Samit Kakkad Films",[130]
102,DEC,21,Zero,Aanand L. Rai,Shah Rukh KhanKatrina KaifAnushka SharmaTigman...,"Red Chillies Entertainment, Colour Yellow Prod...",[131][132]
103,DEC,28,Simmba,Rohit Shetty,Ranveer SinghSara Ali KhanSonu Sood,"Dharma Productions, Reliance Entertainment",[133][134]

Simlarly if you want to make a more diverse dataset you can include movies in the same way as done using american and bollywood movies

In [127]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = "8969d57bd5e646d139a5dd420b898492" #got by signing in tmdb

In [128]:
df = df_american.append(df_bollywood,ignore_index = True)
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.,Director,Cast,Production house
0,JANUARY,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2],NaN,NaN,NaN
1,JANUARY,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3],NaN,NaN,NaN
2,JANUARY,5,Stratton,Momentum Pictures,"Simon West (director); Duncan Falconer, Warren...",[4],NaN,NaN,NaN
3,JANUARY,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5],NaN,NaN,NaN
4,JANUARY,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
368,NOV,30,Rajma Chawal,NaN,NaN,[127],Leena Yadav,Rishi KapoorAnirudh TanwarAmyra Dastur,"SaarthiE, Netflix"
369,DEC,7,Kedarnath,NaN,NaN,[128][129],Abhishek Kapoor,Sushant Singh RajputSara Ali Khan,"RSVP Movies, Guy in the Sky Pictures"
370,DEC,14,Ascharyachakit!,NaN,NaN,[130],Samit Kakkad,Priyanka BoseVaibhav Raj GuptaAnkit RaajAnangs...,"Yoodlee films, Samit Kakkad Films"
371,DEC,21,Zero,NaN,NaN,[131][132],Aanand L. Rai,Shah Rukh KhanKatrina KaifAnushka SharmaTigman...,"Red Chillies Entertainment, Colour Yellow Prod..."
372,DEC,28,Simmba,NaN,NaN,[133][134],Rohit Shetty,Ranveer SinghSara Ali KhanSonu Sood,"Dharma Productions, Reliance Entertainment"

In [129]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_genre(x): # is the movie_title
    genres = []
    try:
        result = tmdb_movie.search(x) #getting that movie
    except TypeError:
        return np.NaN
    movie_id = result[0].id
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
    data_json = response.json() #making json of genres
    if data_json['genres']:
        genre_str = " " 
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres) #return string of genres joined by spaces
    else:
        np.NaN

In [130]:
df_american['genre'] = df_american['Title'].apply(get_genre)
df_american

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.,genre
0,JANUARY,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2],Horror Mystery Thriller
1,JANUARY,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3],Thriller Drama
2,JANUARY,5,Stratton,Momentum Pictures,"Simon West (director); Duncan Falconer, Warren...",[4],Action Thriller
3,JANUARY,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5],Drama History Western
4,JANUARY,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6],Action Thriller
...,...,...,...,...,...,...,...
264,DECEMBER,25,Holmes & Watson,Columbia Pictures / Gary Sanchez Productions,Etan Cohen (director/screenplay); Will Ferrell...,[163],Mystery Adventure Comedy Crime
265,DECEMBER,25,Vice,Annapurna Pictures / Plan B Entertainment,Adam McKay (director/screenplay); Christian Ba...,[137],Thriller Science Fiction Action Adventure
266,DECEMBER,25,On the Basis of Sex,Focus Features,Mimi Leder (director); Daniel Stiepleman (scre...,[226],Drama History
267,DECEMBER,25,Destroyer,Annapurna Pictures,"Karyn Kusama (director); Phil Hay, Matt Manfre...",[258],Thriller Crime Drama Action
268,DECEMBER,28,Black Mirror: Bandersnatch,Netflix,David Slade (director); Charlie Brooker (scree...,[259],Science Fiction Mystery Drama Thriller TV Movie

In [131]:
movie_id = []
l = []
for i in df_bollywood['Title']:
    try:
        result = tmdb_movie.search(i) #getting that movie
    except TypeError:
        l.append(i)
    if(len(result)<1):
        print(result,i)
    else:
        movie_id.append(result[0].id)

[] Falooda
[] Laxmi and Tikli Bomb

In [132]:
#df_bollywood.drop(Title == 'Falooda')
#df_bollywood.drop
print(df_bollywood[df_bollywood['Title'] == 'Falooda'].index)
print(df_bollywood[df_bollywood['Title'] == 'Laxmi and Tikli Bomb'].index)
df_bollywood = df_bollywood.drop([37,57])
df_bollywood.shape

Int64Index([37], dtype='int64')
Int64Index([57], dtype='int64')

(102, 7)

In [133]:
df_bollywood['genre'] = df_bollywood['Title'].apply(get_genre)
df_bollywood

,Opening,Opening.1,Title,Director,Cast,Production house,Ref.,genre
0,JAN,12,1921,Vikram Bhatt,Zareen KhanKaran KundraTobby HinstonSonia Arms...,ASA Productions and Enterprises,[16][17],History Drama
1,JAN,12,Kaalakaandi,Akshat Verma,Saif Ali KhanIsha TalwarShenaz TreasuryAkshay ...,Cinestan Film Company,[18][19],Comedy Thriller Drama
2,JAN,12,Mukkabaaz,Anurag Kashyap,Vineet Kumar SinghZoya HussainRavi KishanJimmy...,"Eros International, Colour Yellow Productions",[20][21],Drama
3,JAN,15,Phir Se...,Kunal Kohli,Jennifer WingetKunal KohliRajit Kapur,"Bombay Film Company Ltd, Netflix",[22][23][24],Romance Drama
4,JAN,19,My Birthday Song,Samir Soni,Sanjay SuriNora FatehiPitobash,Kahwa entertainment,[25][26],Thriller
...,...,...,...,...,...,...,...,...
99,NOV,30,Rajma Chawal,Leena Yadav,Rishi KapoorAnirudh TanwarAmyra Dastur,"SaarthiE, Netflix",[127],Comedy Drama Family
100,DEC,7,Kedarnath,Abhishek Kapoor,Sushant Singh RajputSara Ali Khan,"RSVP Movies, Guy in the Sky Pictures",[128][129],Romance
101,DEC,14,Ascharyachakit!,Samit Kakkad,Priyanka BoseVaibhav Raj GuptaAnkit RaajAnangs...,"Yoodlee films, Samit Kakkad Films",[130],Thriller Drama
102,DEC,21,Zero,Aanand L. Rai,Shah Rukh KhanKatrina KaifAnushka SharmaTigman...,"Red Chillies Entertainment, Colour Yellow Prod...",[131][132],Comedy Drama Family
103,DEC,28,Simmba,Rohit Shetty,Ranveer SinghSara Ali KhanSonu Sood,"Dharma Productions, Reliance Entertainment",[133][134],Action Crime

In [134]:
df_bollywood = df_bollywood[['Title','Director','Cast','genre']]
df_bollywood

,Title,Director,Cast,genre
0,1921,Vikram Bhatt,Zareen KhanKaran KundraTobby HinstonSonia Arms...,History Drama
1,Kaalakaandi,Akshat Verma,Saif Ali KhanIsha TalwarShenaz TreasuryAkshay ...,Comedy Thriller Drama
2,Mukkabaaz,Anurag Kashyap,Vineet Kumar SinghZoya HussainRavi KishanJimmy...,Drama
3,Phir Se...,Kunal Kohli,Jennifer WingetKunal KohliRajit Kapur,Romance Drama
4,My Birthday Song,Samir Soni,Sanjay SuriNora FatehiPitobash,Thriller
...,...,...,...,...
99,Rajma Chawal,Leena Yadav,Rishi KapoorAnirudh TanwarAmyra Dastur,Comedy Drama Family
100,Kedarnath,Abhishek Kapoor,Sushant Singh RajputSara Ali Khan,Romance
101,Ascharyachakit!,Samit Kakkad,Priyanka BoseVaibhav Raj GuptaAnkit RaajAnangs...,Thriller Drama
102,Zero,Aanand L. Rai,Shah Rukh KhanKatrina KaifAnushka SharmaTigman...,Comedy Drama Family
103,Simmba,Rohit Shetty,Ranveer SinghSara Ali KhanSonu Sood,Action Crime

In [135]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [136]:
df_american.columns

Index(['Opening', 'Opening.1', 'Title', 'Production company', 'Cast and crew',
       'Ref.', 'genre'],
      dtype='object')

In [137]:
df_american = df_american[['Title','Cast and crew','genre']]

In [138]:
df_american['Director'] = df_american['Cast and crew'].apply(get_director)

<ipython-input-138-fbfd370e1f31>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['Director'] = df_american['Cast and crew'].apply(get_director)

In [139]:
def get_actor1(x):
    return (x.split("screenplay); ")[-1].split(", ")[0])

In [140]:
#in 2018movies bollywood we cannot have actors as they are joined together we will be only
#using the american movies dataset for 2018 movies

In [141]:
def get_actor2(x):
    if len(x.split("screenplay); ")[-1].split(", ")) <2 :
        return np.NaN
    else:
        return (x.split("screenplay); ")[-1]).split(", ")[1]

In [142]:
def get_actor3(x):
    if len(x.split("screenplay); ")[-1].split(", ")) <3:
        return np.NaN
    else:
        return (x.split("screenplay); ")[-1]).split(", ")[2]

In [143]:
df_american['actor_1_name'] = df_american['Cast and crew'].map(lambda x: get_actor1(x))
df_american['actor_2_name'] = df_american['Cast and crew'].map(lambda x: get_actor2(x))
df_american['actor_3_name'] = df_american['Cast and crew'].map(lambda x: get_actor3(x))

<ipython-input-143-d65b00f7e8af>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['actor_1_name'] = df_american['Cast and crew'].map(lambda x: get_actor1(x))
<ipython-input-143-d65b00f7e8af>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['actor_2_name'] = df_american['Cast and crew'].map(lambda x: get_actor2(x))

In [144]:
df_american.columns

Index(['Title', 'Cast and crew', 'genre', 'Director', 'actor_1_name',
       'actor_2_name', 'actor_3_name'],
      dtype='object')

In [145]:
df_american = df_american.rename(columns={'Title':'movie_title'})
df_american = df_american.rename(columns={'Director':'director_name'})
df_american = df_american.rename(columns={'genre':'genres'})

In [146]:
df_american = df_american.drop(columns = ['Cast and crew'])
df_american

,movie_title,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Insidious: The Last Key,Horror Mystery Thriller,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell
1,The Strange Ones,Thriller Drama,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus
2,Stratton,Action Thriller,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan
3,Sweet Country,Drama History Western,Warwick Thornton,Bryan Brown,Sam Neill,NaN
4,The Commuter,Action Thriller,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson
...,...,...,...,...,...,...
264,Holmes & Watson,Mystery Adventure Comedy Crime,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall
265,Vice,Thriller Science Fiction Action Adventure,Adam McKay,Christian Bale,Amy Adams,Steve Carell
266,On the Basis of Sex,Drama History,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux
267,Destroyer,Thriller Crime Drama Action,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell
268,Black Mirror: Bandersnatch,Science Fiction Mystery Drama Thriller TV Movie,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry

In [147]:
new_data = df_american.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [ ]:
new_data['actor_2_name'] = new_data['actor_2_name'].replace(np.nan, 'unknown')
new_data['actor_3_name'] = new_data['actor_3_name'].replace(np.nan, 'unknown')
new_data['movie_title'] = new_data['movie_title'].str.lower()
new_data['comb'] = new_data['actor_1_name'] + ' ' + new_data['actor_2_name'] + ' '+ new_data['actor_3_name'] + ' '+ new_data['director_name'] +' ' + new_data['genres']

In [149]:
new_data

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Mystery Thriller,insidious: the last key,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller Drama,the strange ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action Thriller,stratton,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Drama History Western,sweet country,Bryan Brown Sam Neill unknown Warwick Thornton...
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller,the commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
...,...,...,...,...,...,...,...
264,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Mystery Adventure Comedy Crime,holmes & watson,Will Ferrell John C. Reilly Rebecca Hall Etan ...
265,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Thriller Science Fiction Action Adventure,vice,Christian Bale Amy Adams Steve Carell Adam McK...
266,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama History,on the basis of sex,Felicity Jones Armie Hammer Justin Theroux Mim...
267,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,Thriller Crime Drama Action,destroyer,Nicole Kidman Sebastian Stan Toby Kebbell Kary...
268,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry,Science Fiction Mystery Drama Thriller TV Movie,black mirror: bandersnatch,Fionn Whitehead Will Poulter Asim Chaudhry Dav...

# Doing the same for 2019

In [150]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [151]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,4,Escape Room,Columbia Pictures,"Adam Robitel (director); Bragi F. Schut, Maria...",[2]
1,JANUARY,4,Rust Creek,IFC Films,Jen McGowan (director); Julie Lipson (screenpl...,[3]
2,JANUARY,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4]
3,JANUARY,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5]
4,JANUARY,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6]
...,...,...,...,...,...,...
237,DECEMBER,25,Spies in Disguise,20th Century Fox / Blue Sky Studios / Chernin ...,"Nick Bruno, Troy Quane (directors); Brad Copel...",[132]
238,DECEMBER,25,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[221]
239,DECEMBER,25,1917,Universal Pictures / DreamWorks Pictures / Ent...,Sam Mendes (director/screenplay); Krysty Wilso...,[222]
240,DECEMBER,25,Just Mercy,Warner Bros. Pictures / Participant Media,"Destin Daniel Cretton (director/screenplay), A...",[223]
241,DECEMBER,27,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[224]

In [152]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [153]:
df_american = df[['Title','Cast and crew','genres']]

In [154]:
df_american['director_name'] = df_american['Cast and crew'].apply(get_director)
df_american['actor_1_name'] = df_american['Cast and crew'].map(lambda x: get_actor1(x))
df_american['actor_2_name'] = df_american['Cast and crew'].map(lambda x: get_actor2(x))
df_american['actor_3_name'] = df_american['Cast and crew'].map(lambda x: get_actor3(x))

<ipython-input-154-7f421a833b5a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['director_name'] = df_american['Cast and crew'].apply(get_director)
<ipython-input-154-7f421a833b5a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['actor_1_name'] = df_american['Cast and crew'].map(lambda x: get_actor1(x))
<ipython-input-154-7f421a833b5a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['actor_2_name'] = df_american['Cast and crew'].map(lambda x: get_actor2(x))

In [156]:
df_american

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Escape Room,"Adam Robitel (director); Bragi F. Schut, Maria...",Thriller Action Mystery Adventure Horror,Adam Robitel,Taylor Russell,Logan Miller,Deborah Ann Woll
1,Rust Creek,Jen McGowan (director); Julie Lipson (screenpl...,Thriller Drama,Jen McGowan,Hermione Corfield,Jay Paulson,Sean O'Bryan
2,American Hangman,Wilson Coneybeare (director/screenplay); Donal...,Thriller,Wilson Coneybeare,Donald Sutherland,Vincent Kartheiser,Oliver Dennis
3,A Dog's Way Home,Charles Martin Smith (director); W. Bruce Came...,Drama Adventure Family,Charles Martin Smith,Bryce Dallas Howard,Edward James Olmos,Alexandra Shipp
4,The Upside,Neil Burger (director); Jon Hartmere (screenpl...,Comedy Drama,Neil Burger,Bryan Cranston,Kevin Hart,Nicole Kidman
...,...,...,...,...,...,...,...
237,Spies in Disguise,"Nick Bruno, Troy Quane (directors); Brad Copel...",Animation Action Adventure Comedy Family,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones
238,Little Women,Greta Gerwig (director/screenplay); Saoirse Ro...,Drama Romance,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh
239,1917,Sam Mendes (director/screenplay); Krysty Wilso...,War Drama Action Thriller,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong
240,Just Mercy,"Destin Daniel Cretton (director/screenplay), A...",Drama Crime History,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson
241,Clemency,Chinonye Chukwu (director/screenplay); Alfre W...,Drama,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge

In [157]:
df_american = df_american.rename(columns={'Title':'movie_title'})
new_data1 = df_american.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [158]:
new_data1['actor_2_name'] = new_data1['actor_2_name'].replace(np.nan, 'unknown')
new_data1['actor_3_name'] = new_data1['actor_3_name'].replace(np.nan, 'unknown')
new_data1['movie_title'] = new_data1['movie_title'].str.lower()
new_data1['comb'] = new_data1['actor_1_name'] + ' ' + new_data1['actor_2_name'] + ' '+ new_data1['actor_3_name'] + ' '+ new_data1['director_name'] +' ' + new_data1['genres']

# For 2020

In [168]:
import bs4 as bs
import urllib.request

In [169]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2020"
source = urllib.request.urlopen(link).read()
soup = bs.BeautifulSoup(source,'lxml')

In [170]:
tables = soup.find_all('table',class_='wikitable sortable') #movies separted into quaters

In [171]:
df1 = pd.read_html(str(tables[0]))[0]
df2 = pd.read_html(str(tables[1]))[0]
df3 = pd.read_html(str(tables[2]))[0]
df4 = pd.read_html(str(tables[3]).replace("'1\"\'",'"1"'))[0] # avoided "ValueError: invalid literal for int() with base 10: '1"'

In [172]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,3,The Grudge,Screen Gems / Stage 6 Films / Ghost House Pict...,Nicolas Pesce (director/screenplay); Andrea Ri...,[2]
1,JANUARY,10,Underwater,20th Century Fox / TSG Entertainment / Chernin...,"William Eubank (director); Brian Duffield, Ada...",[3]
2,JANUARY,10,Like a Boss,Paramount Pictures,"Miguel Arteta (director); Sam Pitman, Adam Col...",[4]
3,JANUARY,10,Three Christs,IFC Films,Jon Avnet (director/screenplay); Eric Nazarian...,NaN
4,JANUARY,10,Inherit the Viper,Barry Films / Tycor International Film Company,Anthony Jerjen (director); Andrew Crabtree (sc...,[5]
...,...,...,...,...,...,...
267,DECEMBER,25,We Can Be Heroes,Netflix / Troublemaker Studios,Robert Rodriguez (director/screenplay); Priyan...,[240]
268,DECEMBER,25,News of the World,Universal Pictures / Perfect World Pictures,Paul Greengrass (director/screenplay); Luke Da...,[241]
269,DECEMBER,25,One Night in Miami...,Amazon Studios,Regina King (director); Kemp Powers (screenpla...,[242]
270,DECEMBER,25,Promising Young Woman,Focus Features / FilmNation Entertainment,Emerald Fennell (director/screenplay); Carey M...,[243]
271,DECEMBER,30,Pieces of a Woman,Netflix / Bron Studios,KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...,[244]

In [173]:
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    if not result:
        return np.NaN
    else:
        movie_id = result[0].id
        response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
        data_json = response.json()
        if data_json['genres']:
            genre_str = " " 
            for i in range(0,len(data_json['genres'])):
                genres.append(data_json['genres'][i]['name'])
            return genre_str.join(genres)
        else:
            return np.NaN

In [174]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [175]:
df_american = df[['Title','Cast and crew','genres']]
df_american

,Title,Cast and crew,genres
0,The Grudge,Nicolas Pesce (director/screenplay); Andrea Ri...,Horror Mystery Thriller
1,Underwater,"William Eubank (director); Brian Duffield, Ada...",Action Horror Science Fiction Thriller
2,Like a Boss,"Miguel Arteta (director); Sam Pitman, Adam Col...",Comedy
3,Three Christs,Jon Avnet (director/screenplay); Eric Nazarian...,Drama
4,Inherit the Viper,Anthony Jerjen (director); Andrew Crabtree (sc...,Drama Thriller Crime
...,...,...,...
267,We Can Be Heroes,Robert Rodriguez (director/screenplay); Priyan...,Action Fantasy Family Comedy
268,News of the World,Paul Greengrass (director/screenplay); Luke Da...,Action Adventure Drama Western
269,One Night in Miami...,Regina King (director); Kemp Powers (screenpla...,Drama
270,Promising Young Woman,Emerald Fennell (director/screenplay); Carey M...,Thriller Crime Drama
271,Pieces of a Woman,KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...,Drama

In [176]:
df_american['director_name'] = df_american['Cast and crew'].map(lambda x: get_director(str(x)))
df_american['actor_1_name'] = df_american['Cast and crew'].map(lambda x: get_actor1(x))
df_american['actor_2_name'] = df_american['Cast and crew'].map(lambda x: get_actor2(x))
df_american['actor_3_name'] = df_american['Cast and crew'].map(lambda x: get_actor3(x))

<ipython-input-176-d789da765bca>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['director_name'] = df_american['Cast and crew'].map(lambda x: get_director(str(x)))
<ipython-input-176-d789da765bca>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['actor_1_name'] = df_american['Cast and crew'].map(lambda x: get_actor1(x))
<ipython-input-176-d789da765bca>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['actor_2_name'] = df_american['Cast and crew'].map(lambda x: get_actor2(x))

In [177]:
df_american = df_american.rename(columns={'Title':'movie_title'})
new_data2 = df_american.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [178]:
new_data2['actor_2_name'] = new_data2['actor_2_name'].replace(np.nan, 'unknown')
new_data2['actor_3_name'] = new_data2['actor_3_name'].replace(np.nan, 'unknown')
new_data2['movie_title'] = new_data2['movie_title'].str.lower()
new_data2['comb'] = new_data2['actor_1_name'] + ' ' + new_data2['actor_2_name'] + ' '+ new_data2['actor_3_name'] + ' '+ new_data2['director_name'] +' ' + new_data2['genres']

In [179]:
new_data2

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Nicolas Pesce,Andrea Riseborough,DemiÃ¡n Bichir,John Cho,Horror Mystery Thriller,the grudge,Andrea Riseborough DemiÃ¡n Bichir John Cho Nico...
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Action Horror Science Fiction Thriller,underwater,Kristen Stewart Vincent Cassel Jessica Henwick...
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,like a boss,Tiffany Haddish Rose Byrne Salma Hayek Miguel ...
3,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Drama,three christs,Richard Gere Peter Dinklage Walton Goggins Jon...
4,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Drama Thriller Crime,inherit the viper,Josh Hartnett Margarita Levieva Chandler Riggs...
...,...,...,...,...,...,...,...
267,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Action Fantasy Family Comedy,we can be heroes,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
268,Paul Greengrass,Tom Hanks,Helena Zengel,unknown,Action Adventure Drama Western,news of the world,Tom Hanks Helena Zengel unknown Paul Greengras...
269,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,one night in miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
270,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller Crime Drama,promising young woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
271,KornÃ©l MundruczÃ³,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,pieces of a woman,Vanessa Kirby Shia LaBeouf Molly Parker KornÃ©l...

# For 2021

In [180]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2021"
source = urllib.request.urlopen(link).read()
soup = bs.BeautifulSoup(source,'lxml')

In [181]:
tables = soup.find_all('table',class_='wikitable sortable')

In [182]:
df1 = pd.read_html(str(tables[0]))[0]
df2 = pd.read_html(str(tables[1]))[0]
df3 = pd.read_html(str(tables[2]))[0]
df4 = pd.read_html(str(tables[3]).replace("'1\"\'",'"1"'))[0]

In [183]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref,Ref.
0,JANUARY,1,Shadow in the Cloud,Vertical Entertainment,Roseanne Liang (director/screenplay); Max Land...,[2],NaN
1,JANUARY,13,The White Tiger,Netflix,Ramin Bahrani (director/screenplay); Adarsh Go...,NaN,NaN
2,JANUARY,14,Locked Down,HBO Max / Warner Bros. Pictures,Doug Liman (director); Steven Knight (screenpl...,[3],NaN
3,JANUARY,15,The Dig,Netflix / Clerkenwell Films,Simon Stone (director); Moira Buffini (screenp...,[4],NaN
4,JANUARY,15,Outside the Wire,Netflix,"Mikael HÃ¥fstrÃ¶m (director); Rob Yescombe, Rowa...",[5],NaN
...,...,...,...,...,...,...,...
200,DECEMBER,22,The Matrix 4,HBO Max / Warner Bros. Pictures / Village Road...,Lana Wachowski (director/screenplay); Aleksand...,NaN,[156]
201,DECEMBER,22,Sing 2,Universal Pictures / Illumination,Garth Jennings (director/screenplay); Matthew ...,NaN,[157]
202,DECEMBER,22,The King's Man,20th Century Studios / Marv Films,Matthew Vaughn (director/screenplay); Karl Gaj...,NaN,[106]
203,DECEMBER,22,Downton Abbey 2,Focus Features / Carnival Films,Simon Curtis (director); Julian Fellowes (scre...,NaN,[158]
204,DECEMBER,25,Cyrano,Metro-Goldwyn-Mayer / Working Title Films,Joe Wright (director); Erica Schmidt (screenpl...,NaN,[153]

In [184]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [185]:
df_american = df[['Title','Cast and crew','genres']]
df_american

,Title,Cast and crew,genres
0,Shadow in the Cloud,Roseanne Liang (director/screenplay); Max Land...,Horror Action War
1,The White Tiger,Ramin Bahrani (director/screenplay); Adarsh Go...,Crime Drama
2,Locked Down,Doug Liman (director); Steven Knight (screenpl...,Comedy Crime Drama
3,The Dig,Simon Stone (director); Moira Buffini (screenp...,Drama History
4,Outside the Wire,"Mikael HÃ¥fstrÃ¶m (director); Rob Yescombe, Rowa...",Thriller Action Science Fiction
...,...,...,...
200,The Matrix 4,Lana Wachowski (director/screenplay); Aleksand...,Action Science Fiction
201,Sing 2,Garth Jennings (director/screenplay); Matthew ...,Music Animation Comedy Family
202,The King's Man,Matthew Vaughn (director/screenplay); Karl Gaj...,Action Adventure Comedy
203,Downton Abbey 2,Simon Curtis (director); Julian Fellowes (scre...,Drama
204,Cyrano,Joe Wright (director); Erica Schmidt (screenpl...,Drama Comedy History Romance

In [186]:
df_american['director_name'] = df_american['Cast and crew'].map(lambda x: get_director(str(x)))
df_american['actor_1_name'] = df_american['Cast and crew'].map(lambda x: get_actor1(x))
df_american['actor_2_name'] = df_american['Cast and crew'].map(lambda x: get_actor2(x))
df_american['actor_3_name'] = df_american['Cast and crew'].map(lambda x: get_actor3(x))

<ipython-input-186-d789da765bca>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['director_name'] = df_american['Cast and crew'].map(lambda x: get_director(str(x)))
<ipython-input-186-d789da765bca>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['actor_1_name'] = df_american['Cast and crew'].map(lambda x: get_actor1(x))
<ipython-input-186-d789da765bca>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['actor_2_name'] = df_american['Cast and crew'].map(lambda x: get_actor2(x))
<ipython-input-186-d789da765bca>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_american['actor_3_name'] = df_american['Cast and crew'].map(lambda x: get_actor3(x))

In [187]:
df_american = df_american.rename(columns={'Title':'movie_title'})
new_data3 = df_american.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [188]:
new_data3['actor_2_name'] = new_data3['actor_2_name'].replace(np.nan, 'unknown')
new_data3['actor_3_name'] = new_data3['actor_3_name'].replace(np.nan, 'unknown')
new_data3['movie_title'] = new_data3['movie_title'].str.lower()
new_data3['comb'] = new_data3['actor_1_name'] + ' ' + new_data3['actor_2_name'] + ' '+ new_data3['actor_3_name'] + ' '+ new_data3['director_name'] +' ' + new_data3['genres']

In [189]:
new_data3

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Roseanne Liang,ChloÃ« Grace Moretz,Taylor John Smith,Beulah Koale,Horror Action War,shadow in the cloud,ChloÃ« Grace Moretz Taylor John Smith Beulah Ko...
1,Ramin Bahrani,Adarsh Gourav,Rajkummar Rao,Priyanka Chopra Jonas,Crime Drama,the white tiger,Adarsh Gourav Rajkummar Rao Priyanka Chopra Jo...
2,Doug Liman,Anne Hathaway,Chiwetel Ejiofor,Stephen Merchant,Comedy Crime Drama,locked down,Anne Hathaway Chiwetel Ejiofor Stephen Merchan...
3,Simon Stone,Carey Mulligan,Ralph Fiennes,Lily James,Drama History,the dig,Carey Mulligan Ralph Fiennes Lily James Simon ...
4,Mikael HÃ¥fstrÃ¶m,Anthony Mackie,Damson Idris,Emily Beecham,Thriller Action Science Fiction,outside the wire,Anthony Mackie Damson Idris Emily Beecham Mika...
...,...,...,...,...,...,...,...
200,Lana Wachowski,Keanu Reeves,Carrie-Anne Moss,Yahya Abdul-Mateen II,Action Science Fiction,the matrix 4,Keanu Reeves Carrie-Anne Moss Yahya Abdul-Mate...
201,Garth Jennings,Matthew McConaughey,Reese Witherspoon,Scarlett Johansson,Music Animation Comedy Family,sing 2,Matthew McConaughey Reese Witherspoon Scarlett...
202,Matthew Vaughn,Ralph Fiennes,Gemma Arterton,Rhys Ifans,Action Adventure Comedy,the king's man,Ralph Fiennes Gemma Arterton Rhys Ifans Matthe...
203,Simon Curtis,Hugh Bonneville,Jim Carter,Michelle Dockery,Drama,downton abbey 2,Hugh Bonneville Jim Carter Michelle Dockery Si...
204,Joe Wright,Peter Dinklage,Haley Bennett,Ben Mendelsohn,Drama Comedy History Romance,cyrano,Peter Dinklage Haley Bennett Ben Mendelsohn Jo...

In [190]:
df_after2017 = new_data.append(new_data1.append(new_data2.append(new_data3,ignore_index = True),ignore_index = True),ignore_index = True)
df_after2017

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Mystery Thriller,insidious: the last key,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller Drama,the strange ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action Thriller,stratton,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Drama History Western,sweet country,Bryan Brown Sam Neill unknown Warwick Thornton...
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller,the commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
...,...,...,...,...,...,...,...
983,Lana Wachowski,Keanu Reeves,Carrie-Anne Moss,Yahya Abdul-Mateen II,Action Science Fiction,the matrix 4,Keanu Reeves Carrie-Anne Moss Yahya Abdul-Mate...
984,Garth Jennings,Matthew McConaughey,Reese Witherspoon,Scarlett Johansson,Music Animation Comedy Family,sing 2,Matthew McConaughey Reese Witherspoon Scarlett...
985,Matthew Vaughn,Ralph Fiennes,Gemma Arterton,Rhys Ifans,Action Adventure Comedy,the king's man,Ralph Fiennes Gemma Arterton Rhys Ifans Matthe...
986,Simon Curtis,Hugh Bonneville,Jim Carter,Michelle Dockery,Drama,downton abbey 2,Hugh Bonneville Jim Carter Michelle Dockery Si...
987,Joe Wright,Peter Dinklage,Haley Bennett,Ben Mendelsohn,Drama Comedy History Romance,cyrano,Peter Dinklage Haley Bennett Ben Mendelsohn Jo...

In [191]:
df_before2017 = pd.read_csv('datasets/moviestill2017.csv')
df_before2017

,Unnamed: 0,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,combined
0,0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Joel David Moore ...
1,1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Orlando Bloom Gore V...
2,2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Rory Kinnear Sam ...
3,3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Christian Bale Christ...
4,4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker Rob Walker Doug Walker ...
...,...,...,...,...,...,...,...,...
5359,524,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,the incredible jessica james,Jessica Williams Chris O'Dowd Chris O'Dowd Jim...
5360,525,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,can't buy my love,Adelaide Kane Benjamin Hollingsworth Benjamin ...
5361,526,Hannaleena Hauru,Inka HaapamÃ¤ki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,thick lashes of lauri mÃ¤ntyvaara,Inka HaapamÃ¤ki Rosa Honkonen Rosa Honkonen Han...
5362,527,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,cop and a half: new recruit,Lou Diamond Phillips Wallace Shawn Wallace Sha...
5363,529,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,mom,Sridevi Kapoor Sajal Ali Sajal Ali Ravi Udyawa...

In [197]:
df_after2017.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           5
movie_title      0
comb             5
dtype: int64

In [198]:
df_after2017 = df_after2017.dropna(how='any')

In [199]:
final_df = df_before2017.append(df_after2017,ignore_index=True)

In [200]:
final_df.isna().sum()

Unnamed: 0        983
director_name       0
actor_1_name        0
actor_2_name        0
actor_3_name        0
genres              0
movie_title         0
combined          983
comb             5364
dtype: int64

In [201]:
final_df['movie_title'] = final_df['movie_title'].str.lower()

In [202]:
final_df.to_csv('main_data.csv',index=False)